---
- hosts: jenkins
  sudo: yes
  connection: ssh
  tasks:
  - name: Install Apache webserver
    yum: 
      name: httpd 
      state: latest
  - name: verify service status
    shell: systemctl status httpd
    register: result
    until: result.stdout.find("active (running)") != -1
    retries: 5
    delay: 5
  - debug: var=result  
